name: create PR
on:
  push:
    branches:
      - material-ui
jobs:
  createPR:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "auto-pr-branch"
          base: main
          title: Automated PR
          commit-message: Automated Commit for material-ui branch
          delete-branch: false
