name: create PR
on:
  push:
    branches:
      - material-ui
jobs:
  createPR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Automated Commit for material-ui branch
          title: Automated PR
          base: main
          labels: automated-pr
          branch: automated-branch
          delete-branch: true
